Particle Factory API (closes architectury#93)
architectury/architectury pull request #110
Opened 2021-06-20 14:31 UTC by Leo40Git

**NOTE:** Currently untested! (hence why it's a draft)

2021-06-20 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/architectury/architectury-api?pullRequest=110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/architectury/architectury-api?pullRequest=110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/architectury/architectury-api?pullRequest=110) it.</sub>

2021-06-20 17:24 UTC, Leo40Git commented
I've added a test to the testmod (summon the test particle via `/particle` - I tried adding a block that randomly creates that particle but that failed).

Also, tested on Fabric 1.16.5.

2021-06-25 12:01 UTC, shedaniel requested changes

2021-06-25 12:01 UTC, shedaniel commented on common/src/main/java/me/shedaniel/architectury/registry/ParticleFactories.java
> +    public interface PendingParticleProvider<T extends ParticleOptions> {
DeferredParticleProvider

2021-06-25 12:01 UTC, shedaniel commented on common/src/main/java/me/shedaniel/architectury/registry/ParticleFactories.java
> +    public static <T extends ParticleOptions> void register(ParticleType<T> type, PendingParticleProvider<T> constructor) {
Param: constructor -> provider
(fix this for the subprojects as well)

2021-06-25 12:09 UTC, MaxNeedsSnacks approved these changes

2021-06-25 15:00 UTC, MaxNeedsSnacks commented
Adding last call since Dan‘s review has been resolved

2021-06-25 15:59 UTC, shedaniel approved these changes

2021-06-27 00:18 UTC, merged