Backported fluid stack fix to 1.20.2
architectury/architectury pull request #485
Opened 2024-03-17 07:18 UTC by Jab125

fix: FluidStackImpl#getRawFluidSupplier crashing on forge/neoforge

2024-03-17 07:23 UTC, shedaniel requested changes

2024-03-17 07:23 UTC, shedaniel commented on forge/src/main/java/dev/architectury/fluid/forge/FluidStackImpl.java
> +        return () -> BuiltInRegistries.FLUID.getHolderOrThrow(BuiltInRegistries.FLUID.getResourceKey(object.getRawFluid()).orElseThrow()).value();
Maybe use a method ref here

2024-03-17 08:18 UTC, Jab125 commented on forge/src/main/java/dev/architectury/fluid/forge/FluidStackImpl.java
> +        return () -> BuiltInRegistries.FLUID.getHolderOrThrow(BuiltInRegistries.FLUID.getResourceKey(object.getRawFluid()).orElseThrow()).value();
It's a direct cherry pick of #483 to 1.20.2

2024-03-19 07:25 UTC, shedaniel approved these changes

2024-03-19 07:25 UTC, merged